# Generated by Django 4.1.6 on 2023-02-09 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FamilyTree",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "gender",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Male"), (2, "Female")], default=1
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.familytree",
                    ),
                ),
            ],
            options={
                "db_table": "family_tree",
            },
        ),
    ]
